[package]
name = "veil_hub"
version = "14.0.0"
authors = []

[addresses]
veil_hub = "0x9516494976a6de49218b86c96cceac7eb0366de6610d068e861b3636beec1915"
supra_oracle = "0x5615001f63d3223f194498787647bb6f8d37b8d1e6773c00dcdd894079e56190"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.core]
git = "https://github.com/Entropy-Foundation/dora-interface"
subdir = "supra/testnet/core"
rev = "master"

[dev-dependencies]